# Generated by Django 4.1 on 2022-08-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='hotess',
            field=models.CharField(max_length=100),
        ),
    ]
