# Generated by Django 4.1 on 2022-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_hotess_face_hotness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('R', 'Rather Not Say')], default='R', max_length=1),
        ),
    ]
