# Generated by Django 4.1 on 2022-08-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
