# Generated by Django 4.1 on 2022-09-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_face_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='hotness',
            new_name='golden_ratio',
        ),
    ]
